### ISSUE TITLE
Dataset not available

### ISSUE THREAD

**Issue by SolicTous** [amberwangyili/neurop#5]
Baidu cloud works only with chinese.
Can you share it on another cloud working for all?

**Comment by amberwangyili** [comment]
I upload the data to Google Drive, here is the link : https://drive.google.com/drive/folders/19AHndewa_cmM3ttbAnu5WZQbv6IcC_bb?usp=drive_link

**Comment by SolicTous** [comment]
Thank you ^_^

**Comment by hpnquoc** [comment]
> I upload the data to Google Drive, here is the link : https://drive.google.com/drive/folders/19AHndewa_cmM3ttbAnu5WZQbv6IcC_bb?usp=drive_link

Hi. can you reup the dataset...
